export const namesA = [
    "Ava", "Amelia",
    'Abigail', 'Avery',
    'Aria', 'Aubrey',
    'Addison', 'Audrey',
    'Aurora', 'Anna',
    'Aaliyah', 'Allison',
    'Adeline', 'Alexa',
    'Autumn', 'Aubree',
    'Arianna', 'Adalynn',
    'Annabelle', 'Alexandra',
    'Ashley', 'Athena',
    'Andrea', 'Alyssa',
    'Adalyn', 'Arya',
    'Ariel', 'Alexis',
    'Aliyah', 'Arabella',
    'Anastasia', 'Amy',
    'Amaya', 'Adaline',
    'Alaina', 'Alina',
    'Angelina', 'Adelyn',
    'Amara', 'Ana',
    'Alana', 'Adriana',
    'Alayna', 'Ayla',
    'Angela', 'Alivia',
    'Alexandria', 'Amiyah',
    'Amina', 'Adelaide',
    'Aniyah', 'Ariella',
    'Annie', 'Adelynn',
    'Alessandra', 'Amira',
    'Arielle', 'Ada',
    'Ariah', 'Aspen',
    'Allie', 'Amanda',
    'Angel', 'Ainsley',
    'Alicia', 'Alondra',
    'Adrianna', 'Addilyn',
    'Alison', 'Annalise',
    'Averie', 'Amber',
    'Alexia', 'Anaya',
    'Amari', 'Ariyah',
    'Aylin', 'Alani',
    'Abby', 'April',
    'Aviana', 'Annabella',
    'Ashlyn', 'Avianna',
    'Allyson', 'Alejandra',
    'Adelina', 'Ashlynn',
    'Aleah', 'Alayah',
    'Angelica', 'Alanna',
    'Addyson', 'Aleena',
    'Aisha', 'Aubrie',
    'Anne', 'Azalea'
]

export const namesB = [
    'Benjamin', 'Brayden',
    'Bryson', 'Bennett',
    'Brooks', 'Braxton',
    'Bentley', 'Beau',
    'Brandon', 'Brody',
    'Blake', 'Bryce',
    'Bella', 'Brooklyn',
    'Brielle', 'Brianna',
    'Bailey', 'Blakely',
    'Brynlee', 'Brooke',
    'Blake', 'Brooklynn'
]

export const namesC = [
    'Charlotte', 'Camila',
    'Chloe', 'Claire',
    'Caroline', 'Cora',
    'Clara', 'Charlie',
    'Cecilia', 'Callie',
    'Catalina', 'Catherine',
    'Carter', 'Christopher',
    'Charles', 'Caleb',
    'Christian', 'Colton',
    'Cameron', 'Connor',
    'Cooper', 'Carson',
    'Chase', 'Cole'
]

export const namesD = [
    'Daniel', 'David',
    'Dylan', 'Dominic',
    'Declan', 'Damian',
    'Diego', 'Dean',
    'Dawson', 'Daxton',
    'Delilah', 'Daisy',
    'Diana', 'Daniela',
    'Dakota', 'Delaney',
    'Destiny', 'Daleyza']

export const namesE = [
    "Emma",
    "Elijah",
    "Evelyn",
    "Ethan",
    "Ezra",
    "Elizabeth",
    "Eleanor",
    "Ella",
    "Emily",
    "Elias",
    "Ellie",
    "Ezekiel",
    "Eli",
    "Emilia",
    "Easton",
    "Eliana",
    "Everly",
    "Everett",
    "Elena",
    "Emmett",
    "Evan",
    "Emery",
    "Emerson",
    "Eden",
    "Eva",
    "Elliott",
    "Elliot",
    "Enzo",
    "Everleigh",
    "Eloise",
    "Eliza",
    "Emiliano",
    "Elliana",
    "Emmanuel",
    "Emersyn",
    "Esther",
    "Ember",
    "Eric",
    "Edward",
    "Emilio",
]

export const namesF = [
    "Finley ",
    "Finn",
    "Felix",
    "Freya",
    "Faith",
    "Francisco",
    "Fiona",
    "Fernando",
    "Finnegan",
    "Fatima",
    "Frances",
    "Franklin",
    "Forrest",
    "Francesca",
    "Francis",
    "Ford",
    "Frankie",
    "Felicity",
    "Frank",
    "Fabian",
    "Finnley",
    "Frederick",
    "Fernanda",
    "Faye",
    "Flora",
    "Flynn",
    "Fletcher",
    "Fallon",
    "Florence",
    "Forest",
    "Franco",
    "Frida",
    "Fisher",
    "Felipe",
    "Fox",
    "Foster",
    "Farrah",
    "Floss",
    "Farah",
    "Fern",
]

export const namesG = [
    "Grayson",
    "Gianna",
    "Gabriel",
    "Grace",
    "Greyson",
    "Genesis",
    "Gael",
    "Gabriella",
    "Giovanni",
    "George",
    "Graham",
    "Gavin",
    "Genevieve",
    "Grant",
    "Georgia",
    "Griffin",
    "Gemma",
    "Gracie",
    "Gia",
    "Gideon",
    "Gianni",
    "Gunner",
    "Gracelynn",
    "Gabriela",
    "Gracelyn",
    "Giselle",
    "Gwendolyn",
    "Garrett",
    "Grady",
    "Gabrielle",
    "Gregory",
    "Gunnar",
    "Gloria",
    "Gerardo",
    "Gage",
    "Grey",
    "Gustavo",
    "Giana",
    "Giuliana",
    "Greta",
]

export const namesH = [
    "Henry",
    "Harper",
    "Hudson",
    "Hazel",
    "Hannah",
    "Hunter",
    "Hayden",
    "Hailey",
    "Harrison",
    "Hadley",
    "Hayes",
    "Holden",
    "Harmony",
    "Harlow",
    "Hope",
    "Harley",
    "Haven",
    "Hallie",
    "Hector",
    "Heidi",
    "Harvey",
    "Hank",
    "Hugo",
    "Helen",
    "Hattie",
    "Holly",
    "Heaven",
    "Helena",
    "Henley",
    "Holland",
    "Hanna",
    "Haley",
    "Huxley",
    "Hezekiah",
    "Harlan",
    "Houston",
    "Hamza",
    "Hadassah",
    "Hayley",
    "Halle",
]

export const namesI = [
    "Isabella",
    "Isaac",
    "Isaiah",
    "Isla",
    "Ivy",
    "Ian",
    "Iris",
    "Isabelle",
    "Ivan",
    "Isabel",
    "Israel",
    "Ismael",
    "Izabella",
    "Ibrahim",
    "Imani",
    "Isaias",
    "Ivory",
    "Itzel",
    "Izaiah",
    "Ivanna",
    "Ira",
    "Irene",
    "Issac",
    "Indigo",
    "Ila",
    "Isabela",
    "Iliana",
    "India",
    "Idris",
    "Ishaan",
    "Ingrid",
    "Isa",
    "Ignacio",
    "Ida",
    "Ivana",
    "Inaya",
    "Indiana",
    "Imogen",
    "Iman",
    "Immanuel",
]