export const namesA = [
    "Ava", "Amelia",
    'Abigail', 'Avery',
    'Aria', 'Aubrey',
    'Addison', 'Audrey',
    'Aurora', 'Anna',
    'Aaliyah', 'Allison',
    'Adeline', 'Alexa',
    'Autumn', 'Aubree',
    'Arianna', 'Adalynn',
    'Annabelle', 'Alexandra',
    'Ashley', 'Athena',
    'Andrea', 'Alyssa',
    'Adalyn', 'Arya',
    'Ariel', 'Alexis',
    'Aliyah', 'Arabella',
    'Anastasia', 'Amy',
    'Amaya', 'Adaline',
    'Alaina', 'Alina',
    'Angelina', 'Adelyn',
    'Amara', 'Ana',
    'Alana', 'Adriana',
    'Alayna', 'Ayla',
    'Angela', 'Alivia',
    'Alexandria', 'Amiyah',
    'Amina', 'Adelaide',
    'Aniyah', 'Ariella',
    'Annie', 'Adelynn',
    'Alessandra', 'Amira',
    'Arielle', 'Ada',
    'Ariah', 'Aspen',
    'Allie', 'Amanda',
    'Angel', 'Ainsley',
    'Alicia', 'Alondra',
    'Adrianna', 'Addilyn',
    'Alison', 'Annalise',
    'Averie', 'Amber',
    'Alexia', 'Anaya',
    'Amari', 'Ariyah',
    'Aylin', 'Alani',
    'Abby', 'April',
    'Aviana', 'Annabella',
    'Ashlyn', 'Avianna',
    'Allyson', 'Alejandra',
    'Adelina', 'Ashlynn',
    'Aleah', 'Alayah',
    'Angelica', 'Alanna',
    'Addyson', 'Aleena',
    'Aisha', 'Aubrie',
    'Anne', 'Azalea'
]

export const namesB = [
    'Benjamin', 'Brayden',
    'Bryson', 'Bennett',
    'Brooks', 'Braxton',
    'Bentley', 'Beau',
    'Brandon', 'Brody',
    'Blake', 'Bryce',
    'Bella', 'Brooklyn',
    'Brielle', 'Brianna',
    'Bailey', 'Blakely',
    'Brynlee', 'Brooke',
    'Blake', 'Brooklynn'
]

export const namesC = [
    'Charlotte', 'Camila',
    'Chloe', 'Claire',
    'Caroline', 'Cora',
    'Clara', 'Charlie',
    'Cecilia', 'Callie',
    'Catalina', 'Catherine',
    'Carter', 'Christopher',
    'Charles', 'Caleb',
    'Christian', 'Colton',
    'Cameron', 'Connor',
    'Cooper', 'Carson',
    'Chase', 'Cole'
]

export const namesD = [
    'Daniel', 'David',
    'Dylan', 'Dominic',
    'Declan', 'Damian',
    'Diego', 'Dean',
    'Dawson', 'Daxton',
    'Delilah', 'Daisy',
    'Diana', 'Daniela',
    'Dakota', 'Delaney',
    'Destiny', 'Daleyza']

export const namesE = [
    "Emma",
    "Elijah",
    "Evelyn",
    "Ethan",
    "Ezra",
    "Elizabeth",
    "Eleanor",
    "Ella",
    "Emily",
    "Elias",
    "Ellie",
    "Ezekiel",
    "Eli",
    "Emilia",
    "Easton",
    "Eliana",
    "Everly",
    "Everett",
    "Elena",
    "Emmett",
    "Evan",
    "Emery",
    "Emerson",
    "Eden",
    "Eva",
    "Elliott",
    "Elliot",
    "Enzo",
    "Everleigh",
    "Eloise",
    "Eliza",
    "Emiliano",
    "Elliana",
    "Emmanuel",
    "Emersyn",
    "Esther",
    "Ember",
    "Eric",
    "Edward",
    "Emilio",
]

export const namesF = [
    "Finley ",
    "Finn",
    "Felix",
    "Freya",
    "Faith",
    "Francisco",
    "Fiona",
    "Fernando",
    "Finnegan",
    "Fatima",
    "Frances",
    "Franklin",
    "Forrest",
    "Francesca",
    "Francis",
    "Ford",
    "Frankie",
    "Felicity",
    "Frank",
    "Fabian",
    "Finnley",
    "Frederick",
    "Fernanda",
    "Faye",
    "Flora",
    "Flynn",
    "Fletcher",
    "Fallon",
    "Florence",
    "Forest",
    "Franco",
    "Frida",
    "Fisher",
    "Felipe",
    "Fox",
    "Foster",
    "Farrah",
    "Floss",
    "Farah",
    "Fern",
]

export const namesG = [
    "Grayson",
    "Gianna",
    "Gabriel",
    "Grace",
    "Greyson",
    "Genesis",
    "Gael",
    "Gabriella",
    "Giovanni",
    "George",
    "Graham",
    "Gavin",
    "Genevieve",
    "Grant",
    "Georgia",
    "Griffin",
    "Gemma",
    "Gracie",
    "Gia",
    "Gideon",
    "Gianni",
    "Gunner",
    "Gracelynn",
    "Gabriela",
    "Gracelyn",
    "Giselle",
    "Gwendolyn",
    "Garrett",
    "Grady",
    "Gabrielle",
    "Gregory",
    "Gunnar",
    "Gloria",
    "Gerardo",
    "Gage",
    "Grey",
    "Gustavo",
    "Giana",
    "Giuliana",
    "Greta",
]

export const namesH = [
    "Henry",
    "Harper",
    "Hudson",
    "Hazel",
    "Hannah",
    "Hunter",
    "Hayden",
    "Hailey",
    "Harrison",
    "Hadley",
    "Hayes",
    "Holden",
    "Harmony",
    "Harlow",
    "Hope",
    "Harley",
    "Haven",
    "Hallie",
    "Hector",
    "Heidi",
    "Harvey",
    "Hank",
    "Hugo",
    "Helen",
    "Hattie",
    "Holly",
    "Heaven",
    "Helena",
    "Henley",
    "Holland",
    "Hanna",
    "Haley",
    "Huxley",
    "Hezekiah",
    "Harlan",
    "Houston",
    "Hamza",
    "Hadassah",
    "Hayley",
    "Halle",
]

export const namesI = [
    "Isabella",
    "Isaac",
    "Isaiah",
    "Isla",
    "Ivy",
    "Ian",
    "Iris",
    "Isabelle",
    "Ivan",
    "Isabel",
    "Israel",
    "Ismael",
    "Izabella",
    "Ibrahim",
    "Imani",
    "Isaias",
    "Ivory",
    "Itzel",
    "Izaiah",
    "Ivanna",
    "Ira",
    "Irene",
    "Issac",
    "Indigo",
    "Ila",
    "Isabela",
    "Iliana",
    "India",
    "Idris",
    "Ishaan",
    "Ingrid",
    "Isa",
    "Ignacio",
    "Ida",
    "Ivana",
    "Inaya",
    "Indiana",
    "Imogen",
    "Iman",
    "Immanuel",
]

export const namesJ = [
    "James",
    "Jack",
    "Jackson",
    "Jacob",
    "John",
    "Joseph",
    "Julian",
    "Jayden",
    "Josiah",
    "Jaxon",
    "Joshua",
    "Jordan",
    "Jonathan",
    "Jameson",
    "Jeremiah",
    "Jose",
    "Jace",
    "Jaxson",
    "Josephine",
    "Jasper",
    "Jade",
    "Jason",
    "Jonah",
    "Jude",
    "Jayce",
    "Julia",
    "Juan",
    "Jesus",
    "Josie",
    "Justin",
    "Judah",
    "Juniper",
    "Jesse",
    "Joel",
    "June",
    "Jasmine",
    "Juliette",
    "Jordyn",
    "Jett",
    "Jeremy",
]

export const namesK = [
    "Kai",
    "Kinsley",
    "Kayden",
    "Kennedy",
    "Kingston",
    "Kaiden",
    "Karter",
    "Kevin",
    "King",
    "Kaylee",
    "Kyrie",
    "Katherine",
    "Kylie",
    "Knox",
    "Khloe",
    "Kyler",
    "Kaleb",
    "Kenneth",
    "Kimberly",
    "Kaden",
    "Kamila",
    "Kaia",
    "Kendall",
    "Kayla",
    "Kobe",
    "Kali",
    "Kamari",
    "Khalil",
    "Karson",
    "Kailani",
    "Kalani",
    "Kane",
    "Kameron",
    "Kiara",
    "Killian",
    "Kyle",
    "Kamryn",
    "Kade",
    "Kira",
    "Kate",
]

export const namesL = [
    "Liam",
    "Lucas",
    "Logan",
    "Levi",
    "Luna",
    "Leo",
    "Luke",
    "Luca",
    "Lincoln",
    "Layla",
    "Lily",
    "Landon",
    "Lucy",
    "Leah",
    "Lillian",
    "Leonardo",
    "Leilani",
    "Luka",
    "Lydia",
    "Lorenzo",
    "Luis",
    "Liliana",
    "Lyla",
    "Leon",
    "Lucia",
    "Lennox",
    "Lennon",
    "Lukas",
    "London",
    "Lane",
    "Louis",
    "Leila",
    "Lilly",
    "Lila",
    "Laila",
    "Lilah",
    "Lainey",
    "Lola",
    "Lilith",
    "Lucille",
]

export const namesM = [
    "Mia",
    "Mateo",
    "Mason",
    "Michael",
    "Matthew",
    "Maverick",
    "Mila",
    "Madison",
    "Miles",
    "Maya",
    "Micah",
    "Madelyn",
    "Myles",
    "Milo",
    "Madeline",
    "Maria",
    "Max",
    "Melody",
    "Maxwell",
    "Matteo",
    "Mackenzie",
    "Maddox",
    "Malachi",
    "Maeve",
    "Margaret",
    "Melanie",
    "Mary",
    "Magnolia",
    "Miguel",
    "Morgan",
    "Matias",
    "Millie",
    "Marcus",
    "Molly",
    "Marley",
    "Margot",
    "Mark",
    "Maximus",
    "Myla",
    "Milan",
]

export const namesN = [
    "Noah",
    "Nora",
    "Nova",
    "Nathan",
    "Nolan",
    "Naomi",
    "Natalie",
    "Nicholas",
    "Natalia",
    "Nevaeh",
    "Nathaniel",
    "Nicolas",
    "Norah",
    "Nash",
    "Noelle",
    "Nico",
    "Nyla",
    "Niko",
    "Noa",
    "Nina",
    "Noel",
    "Nicole",
    "Nasir",
    "Nylah",
    "Nehemiah",
    "Nadia",
    "Nikolai",
    "Nia",
    "Nola",
    "Nalani",
    "Nikolas",
    "Naya",
    "Noemi",
    "Nixon",
    "Nala",
    "Nellie",
    "Novalee",
    "Noor",
    "Neil",
    "Nelson",
]

export const namesO = [
    "Olivia",
    "Oliver",
    "Owen",
    "Oakley",
    "Oscar",
    "Olive",
    "Omar",
    "Octavia",
    "Orion",
    "Ophelia",
    "Odin",
    "Otto",
    "Onyx",
    "Oaklee",
    "Ocean",
    "Omari",
    "Opal",
    "Oakleigh",
    "Otis",
    "Ozzy",
    "Orlando",
    "Ollie",
    "Osiris",
    "Osman",
    "Ozias",
    "Oren",
    "Odette",
    "Ozzie",
    "Oriana",
    "Odessa",
    "Oskar",
    "Osvaldo",
    "Octavio",
    "Olin",
    "Obadiah",
    "Orson",
    "Octavius",
    "Orin",
    "Ofelia",
]

export const namesP = [
    "Penelope",
    "Parker",
    "Paisley",
    "Peyton",
    "Piper",
    "Phoenix",
    "Patrick",
    "Peter",
    "Presley",
    "Preston",
    "Paxton",
    "Paul",
    "Payton",
    "Phoebe",
    "Palmer",
    "Paige",
    "Prince",
    "Poppy",
    "Pablo",
    "Porter",
    "Paris",
    "Pedro",
    "Philip",
    "Princeton",
    "Pierce",
    "Phillip",
    "Priscilla",
    "Penny",
    "Pearl",
    "Persephone",
    "Paulina",
    "Paula",
    "Paloma",
    "Princess",
    "Paola",
    "Pembroke",
    "Perry",
    "Patience",
    "Patricia",
]